name: Push it, push it
on:
  [workflow_dispatch]

jobs:
  publish_image:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: build
        run: |
          docker build . -t cdami/autobuildonhub:latest
      - name: publish
        run: |
          docker login -u cdami -p ${{ secrets.DOCKER_HUB_TOKEN }}
          docker push cdami/autobuildonhub:latest

